#!/usr/bin/env python3

import requests
import argparse
import json

def main():   
    parser = argparse.ArgumentParser(description="Special Agent for Fritzbox")
    parser.add_argument("--host", required=True, help="Fritzbox IP or hostname")
    parser.add_argument("--username", required=True, help="Username for Fritzbox login")
    parser.add_argument("--password", required=True, help="Password for Fritzbox login")
    args = parser.parse_args()


    data = {
        "host": args.host,
        "username": args.username,
        "password": args.password
    }

    print("<<<fritzbox_smarthome>>>")
    print(json.dumps(data))

if __name__ == "__main__":
    main()
